### ISSUE TITLE
Multiproc number of cpus possibly n*n?

### ISSUE THREAD

**Issue by eliaw-twist** [jwillis0720/sadie#26]
https://github.com/jwillis0720/sadie/blob/8448fdad0866656b2906a6a154e09bf0ddb990e1/src/sadie/anarci/anarci.py#L395

I'm not as familiar with multiprocessing as I'd like to be, but would this potentially overload the number of processes if you are executing `run_multiple`?  Since it is passing N (number of cpus) to the mp pool, then N again to hmmer within that call, could this potentially try to use N*N number of cpus?

**Comment by jwillis0720** [comment]
Yes, you are correct. hmmer subprocessing is using multiproc too, creating an NxN. Thanks for the help!
