### ISSUE TITLE
Pandas > 1.35

### ISSUE THREAD

**Issue by jwillis0720** [jwillis0720/sadie#55]
Pandas > 1.35 breaks our subclassing modules.

**Comment by tmsincomb** [comment]
For test https://github.com/jwillis0720/sadie/blob/main/tests/integration/airr/test_airr_intergration.py#L290 it breaks when I update the code to handle pandas 1.4. I found the issue to be here
```python
# Old correct_indel()

In [1]: catnap_heavy = airr_api.run_fasta(heavy_file)  # calls correct_indel by default
In [2]: {'germline_alignment_aa_corrected', 'v_germline_alignment_aa_corrected'} & set(catnap_heavy.columns)
Out[1]: set()

# New correct_indel()

In [1]: catnap_heavy = airr_api.run_fasta(heavy_file)  # calls correct_indel by default
In [2]: {'germline_alignment_aa_corrected', 'v_germline_alignment_aa_corrected'} & set(catnap_heavy.columns)
Out[1]: {'germline_alignment_aa_corrected', 'v_germline_alignment_aa_corrected'}
```
Where the correct_indel() function does not correctly update self. The catnap_heavy_airrtable.feather is missing the 2 columns with the fixed self update. catnap_light_airrtable.feather had the columns {'germline_alignment_aa_corrected', 'v_germline_alignment_aa_corrected'} already so the tests artificially passed

**Comment by tmsincomb** [comment]
Added the missing columns and the Pandas 1.4 tests work now. Do a final run then I push to dev

**Comment by tmsincomb** [comment]
#67
