### ISSUE TITLE
Is there a way of configuring the verbosity of the run_single function in airr library log output

### ISSUE THREAD

**Issue by adamwoolfe** [jwillis0720/sadie#79]
Hi, currently the output of the run_single function has a lot of logging output to standard out. Is there a way to control the verbosity?

**Comment by jwillis0720** [comment]
Hi @adamwoolfe , since it uses the built in python logger, you can control the level by changing the root level logging by placing the following lines at the top of your script/notebook

```
import logging

logger = logging.getLogger()
logger.setLevel('WARNING')
```

**Comment by adamwoolfe** [comment]
Hi Jordan, that works great, thanks!
