### ISSUE TITLE
Documentation formatting messed up

### ISSUE THREAD

**Issue by jwillis0720** [jwillis0720/sadie#83]
I can't figure out why, but something happened with the documentation:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/775977/168213970-111483c0-bc67-4556-a7d5-0545b84bbf1f.png">

Need to fix that 1 and 2

**Comment by tmsincomb** [comment]
This looks like it was indirectly fixed. 
<img width="770" alt="Screen Shot 2022-05-19 at 11 02 57 AM" src="https://user-images.githubusercontent.com/20929725/169368445-a0163995-4302-42cc-84e1-4bbd3a5ac5cc.png">
